steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/errors-fail', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/errors-fail']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'errors-fail', '--image', 'gcr.io/${PROJECT_ID}/errors-fail', '--region', 'us-east4', '--platform', 'managed']
- name: 'hashicorp/terraform'
  args: ['init', 'deployments']
- name: 'hashicorp/terraform'
  args: ['apply', '-auto-approve', 'deployments']
